package ec.com.rp3.demo.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

import ec.com.rp3.demo.db.Contract;

public class CheckListTemplate extends rp3.data.entity.EntityBase<CheckListTemplate> {

	private long id;
	private String label;
	private boolean checked;
	
	@Override
	public long getID() {		
		return id;
	}
	@Override
	public void setID(long id) {
		this.id = id;
	}
	
	@Override
	public boolean isAutoGeneratedId() {		
		return true;
	}
	@Override
	public String getTableName() {		
		return Contract.CheckListTemplate.TABLE_NAME;
	}
	@Override
	public void setValues() {		
	}
	@Override
	public Object getValue(String key) {		
		return null;
	}
	@Override
	public String getDescription() {		
		return this.label;
	}
	
	public String getLabel(){
		return this.label;
	}
	
	public void setLabel(String label){
		this.label = label;
	}
	
	public boolean checked(){
		return this.checked;
	}
	
	public void setChecked(boolean checked){
		this.checked = checked;
	}
	
	public static List<CheckListTemplate> getCheckListTemplate(DataBase db){
		Cursor c = db.query(Contract.CheckListTemplate.TABLE_NAME, new String[] {
				Contract.CheckListTemplate._ID,
				Contract.CheckListTemplate.COLUMN_LABEL
		});
		
		List<CheckListTemplate> list = new ArrayList<CheckListTemplate>();
		while(c.moveToNext()){
			CheckListTemplate t = new CheckListTemplate();
			t.setID(CursorUtils.getLong(c, Contract.CheckListTemplate._ID) );
			t.setLabel( CursorUtils.getString(c, Contract.CheckListTemplate.COLUMN_LABEL));
			list.add(t);
		}
		return list;
	}
	
	
}
