package ec.com.rp3.demo.models;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import android.database.Cursor;

import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

import ec.com.rp3.demo.db.Contract;

public class CheckList extends rp3.data.entity.EntityBase<CheckList> {

	private long id;
	private String user;
	private String code;
	private String label;
	private boolean check;
	private Date date;
	private double latitude;
    private double longitude;
    private String address;
    private String client;
	
	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return true;
	}

	@Override
	public String getTableName() {		
		return Contract.CheckList.TABLE_NAME;
	}

	@Override
	public void setValues() {		
		setValue(Contract.CheckList.COLUMN_ADDRESS, this.address);
		setValue(Contract.CheckList.COLUMN_CHECK, this.check);
		setValue(Contract.CheckList.COLUMN_CODE, this.code);
		setValue(Contract.CheckList.COLUMN_DATE, this.date);
		setValue(Contract.CheckList.COLUMN_LABEL, this.label);
		setValue(Contract.CheckList.COLUMN_LATITUDE, this.latitude);
		setValue(Contract.CheckList.COLUMN_LONGITUDE, this.longitude);
		setValue(Contract.CheckList.COLUMN_USER, this.user);
		setValue(Contract.CheckList.COLUMN_CLIENT, this.client);
	}

	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return this.label;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public boolean isCheck() {
		return check;
	}

	public void setCheck(boolean check) {
		this.check = check;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getClient() {
		return client;
	}

	public void setClient(String client) {
		this.client = client;
	}

	public static List<CheckList> getCheckList(DataBase db, String code){
		Cursor c = db.query(Contract.CheckList.TABLE_NAME, new String[]{
				Contract.CheckList.COLUMN_ADDRESS,
				Contract.CheckList.COLUMN_CHECK,
				Contract.CheckList.COLUMN_CODE,
				Contract.CheckList.COLUMN_DATE,
				Contract.CheckList.COLUMN_LABEL,
				Contract.CheckList.COLUMN_LATITUDE,
				Contract.CheckList.COLUMN_LONGITUDE,
				Contract.CheckList.COLUMN_USER,
				Contract.CheckList.COLUMN_CLIENT	
		}, Contract.CheckList.COLUMN_CODE + " = ?", code);
		
		List<CheckList> list = new ArrayList<CheckList>();
		while(c.moveToNext()){
			CheckList check = new CheckList();
			check.setAddress( CursorUtils.getString(c, Contract.CheckList.COLUMN_ADDRESS) );
			check.setCheck( CursorUtils.getBoolean(c, Contract.CheckList.COLUMN_CHECK) );
			check.setClient( CursorUtils.getString(c, Contract.CheckList.COLUMN_CLIENT) );
			check.setCode( CursorUtils.getString(c, Contract.CheckList.COLUMN_CODE) );
			check.setDate( CursorUtils.getDate(c, Contract.CheckList.COLUMN_DATE) );
			check.setLabel( CursorUtils.getString(c, Contract.CheckList.COLUMN_LABEL) );
			check.setLatitude( CursorUtils.getDouble(c, Contract.CheckList.COLUMN_LATITUDE) );
			check.setLongitude( CursorUtils.getDouble(c, Contract.CheckList.COLUMN_LONGITUDE) );
			check.setUser( CursorUtils.getString(c, Contract.CheckList.COLUMN_USER) );
			list.add(check);
		}
		return list;
	}
	
	
}
