package ec.com.rp3.demo.models;

import java.util.Date;

import android.database.Cursor;

import ec.com.rp3.demo.db.Contract;

import rp3.data.entity.EntityBase;
import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;
import rp3.util.DateTime;

public class CodeScan extends EntityBase<CodeScan> {

	private long id;
	private Date scanDate;
	private String code;
	private double longitude;
	private double latitude;
	private String user;	
	private String address;

	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return true;
	}

	@Override
	public String getTableName() {		
		return Contract.CodeScan.TABLE_NAME;
	}

	@Override
	public void setValues() {			
		setValue(Contract.CodeScan.COLUMN_CODE, this.code);
		setValue(Contract.CodeScan.COLUMN_SCAN_DATE, this.scanDate);
		setValue(Contract.CodeScan.COLUMN_LATITUDE, this.latitude);
		setValue(Contract.CodeScan.COLUMN_LONGITUDE, this.longitude);
		setValue(Contract.CodeScan.COLUMN_USER, this.user);
		setValue(Contract.CodeScan.COLUMN_ADDRESS, this.address);
	}

	@Override
	public Object getValue(String key) {		
		return null;
	}

	@Override
	public String getDescription() {		
		return null;
	}

	public Date getScanDate() {
		return scanDate;
	}

	public void setScanDate(Date scanDate) {
		this.scanDate = scanDate;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public double getLongitude() {
		return longitude;
	}

	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}

	public double getLatitude() {
		return latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}	
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	protected void onBeforeInsert() {		
		super.onBeforeInsert();
		this.setScanDate(DateTime.getCurrentDateTime());
	}
	
	public static CodeScan getCodeScan(DataBase db, long id){
		CodeScan scan = null;
		
		Cursor c = db.query(Contract.CodeScan.TABLE_NAME, new String[] {
			Contract.CodeScan.COLUMN_ADDRESS,
			Contract.CodeScan.COLUMN_CODE,
			Contract.CodeScan.COLUMN_LATITUDE,
			Contract.CodeScan.COLUMN_LONGITUDE,
			Contract.CodeScan.COLUMN_SCAN_DATE,
			Contract.CodeScan.COLUMN_USER,
			Contract.CodeScan._ID
		}, Contract.CodeScan._ID + " = ?", id);
		
		if(c.moveToFirst()){
			scan = new CodeScan();
			scan.setID(id);
			scan.setAddress( CursorUtils.getString(c,Contract.CodeScan.FIELD_ADDRESS) );
			scan.setCode( CursorUtils.getString(c,Contract.CodeScan.FIELD_CODE) );
			scan.setLatitude( CursorUtils.getDouble(c,Contract.CodeScan.FIELD_LATITUDE) );
			scan.setLongitude( CursorUtils.getDouble(c,Contract.CodeScan.FIELD_LONGITUDE) );
			scan.setScanDate( CursorUtils.getDate(c,Contract.CodeScan.FIELD_SCAN_DATE) );
			scan.setUser( CursorUtils.getString(c,Contract.CodeScan.FIELD_USER) );
		}
		
		return scan;		
	}
}
