package ec.com.rp3.demo.models;

import java.util.ArrayList;
import java.util.List;

import android.database.Cursor;

import rp3.db.sqlite.DataBase;
import rp3.util.CursorUtils;

import ec.com.rp3.demo.db.Contract;

public class Product extends rp3.data.entity.EntityBase<Product> {

	private long id;
	private String name;
	
	@Override
	public long getID() {		
		return id;
	}

	@Override
	public void setID(long id) {
		this.id = id;		
	}

	@Override
	public boolean isAutoGeneratedId() {		
		return true;
	}

	@Override
	public String getTableName() {		
		return Contract.Product.TABLE_NAME;
	}

	@Override
	public void setValues() {		
	}

	@Override
	public Object getValue(String key) {	
		return null;
	}

	@Override
	public String getDescription() {
		return name;
	}
	
	public String getName(){
		return this.name;
	}
	
	public void setName(String name){
		this.name = name;
	}

	public static List<Product> getProducts(DataBase db){
		Cursor c = db.query(Contract.Product.TABLE_NAME, 
				new String[]{
					Contract.Product._ID,
					Contract.Product.COLUMN_NAME
						});
		
		List<Product> list = new ArrayList<Product>();
		
		while(c.moveToNext()){
			Product p = new Product();
			p.setID(CursorUtils.getLong(c, Contract.Product._ID));
			p.setName(CursorUtils.getString(c, Contract.Product.FIELD_NAME));
			
			list.add(p);
		}
		
		return list;
	}
	
}
